#! /usr/bin/env bash
set -e
mkdir tmp
make certs

{
  echo 'server: go run main.go --services=server'
  echo 'client: go run main.go --services=client'
  echo 'test: timeout 120 bash ./test/functional-suite && suite.ok'
} | hivemind -

[ -f suite.ok ]
