name: checks
on:
  pull_request:
  push:
    branches: master
jobs:
  test:
    runs-on: nix
    strategy:
      matrix:
        arch: [x86_64-linux]
    steps:
      - uses: actions/checkout@v3
      - run: nix develop .#devShells.${{ matrix.arch }}.default --command make test
